name: iris_app
description: Iris, aplicativo mobile para ajudar deficientes visuais a controlar sua saÃºde. Para seu funcionamento
publish_to: 'pucminas.br.irisapp' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets\\icon\\logoIcone.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets\\icon\\logoIcone.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets\\icon\\logoIcone.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets\\icon\\logoIcone.png"

flutter:
  assets:
    - assets/images/hardware.png
    - assets/images/logo.png
    - assets/icon/logoIcone.png
    - assets/images/acc_finale.png
    - assets/images/balanca.png
    - assets/images/esp32.png
    - assets/images/sensor.png
    - assets/images/termometro.png

  uses-material-design: true
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
